db:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  pass: ''
  name: 'msgr_db'
server:
  host: '127.0.0.1:8081'
debug:
  switch: 'off'
  login: 'on'
  cors: 'on'
bot:
  apiUrl: 'https://api.telegram.org/bot'
  token: ''
  getUpdate: 'request' # how to get update (webhook/request)
  methods: # methods for request start with "/"
    sendMessage: "/sendMessage"